version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SOCKET_PORT=8080
      - CLIENT_URL=https://your-domain.com # Измените на ваш домен
    restart: always

  coturn:
    image: coturn/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    environment:
      - TURN_USERNAME=your_username # Измените на ваше имя пользователя
      - TURN_PASSWORD=your_password # Измените на ваш пароль
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # Папка для SSL-сертификатов
    depends_on:
      - app
    restart: always 